"""2nd migrate

Revision ID: b12fb599d7db
Revises: f9420e9a3224
Create Date: 2022-12-17 13:09:30.298284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12fb599d7db'
down_revision = 'f9420e9a3224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_calc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('z_score', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample_calc', schema=None) as batch_op:
        batch_op.drop_column('z_score')

    # ### end Alembic commands ###
